// React/src/application/App.jsx
import "./App.css";
import Search from "./search/Search";
import Radio from "./radio/Radio";
import { fetchTasks, removeTask, updateTask } from "./core/TaskService";
import { useEffect, useState } from "react";

function check(task) {
  task.completed = !task.completed;
  updateTask(task);

  window.location.reload(false); // hacky way to reload
}

function remove(task) {
  removeTask(task.id);
  window.location.reload(false); // hacky way to reload
}

function App() {
  const [tasks, setTasks] = useState([]);
  const [selectedOption, setSelectedOption] = useState("");
  const [filterText, setFilterText] = useState("");

  async function updateTasks(result) {
    setTasks(await result);
  }

  async function refresh(filterText, selectedOption) {
    console.log("parent: refresh");
    let result = await fetchTasks(filterText, selectedOption);
    updateTasks(result);
  }

  useEffect(() => {
    refresh(filterText, selectedOption);
  }, []);

  return (
    <div>
      <Radio
        selectedOption={selectedOption}
        handleChange={(event) => {
          setSelectedOption(event.target.value);
          refresh(filterText, event.target.value);
        }}
      ></Radio>

      {/* search button */}
      <Search
        filterText={filterText}
        isCompleted={selectedOption}
        onFilterChange={(event) => {
          setFilterText(event.target.value);
          refresh(event.target.value, selectedOption);
        }}
      ></Search>

      {/* Tasks is below*/}
      <div>
        {tasks.map((task, index) => (
          <div key={task.id}>
            <input
              key={task.id + "input"}
              className={"css-input " + (task.completed ? "completed" : "")}
              defaultValue={task.message}
              onChange={(e) => {
                tasks[index].message = e.target.value;
                updateTask(tasks[index]);
              }}
            />

            <div>
              <button
                key={task.id + "check"}
                className="coolButton"
                onClick={() => {
                  check(task);
                }}
              >
                Check
              </button>

              <button
                key={task.id + "remove"}
                className="coolButton"
                onClick={() => remove(task)}
              >
                Remove
              </button>

              <button
                key={task.id + "update"}
                className="coolButton"
                onClick={() => updateTask(task)}
              >
                Update
              </button>
            </div>
            <br />
            <br />
          </div>
        ))}
      </div>
    </div>
  );
}

export default App;

// Angular/src/app/app.component.ts
import {Component, Injectable, OnInit} from '@angular/core';
import {Task, TaskService} from "./TaskService";
import {FormControl, FormGroup} from "@angular/forms";

@Component({
    selector: 'app-root',
    templateUrl: './app.component.html',
    styleUrls: ['./app.component.css']
})
@Injectable()
export class AppComponent implements OnInit {
    title = 'my-app';
    tasks: Task[] = []
    filterText: string = ""
    isCompleted: boolean | null = null
    isCompletedForm: any;

    constructor(private taskService: TaskService) {
    }

    ngOnInit(): void {
        let filterText = ''
        let isCompleted = false

        this.isCompletedForm = new FormGroup({
            isCompleted: new FormControl(),
        });

        this.updateTasks()
    }

    public updateTasks() {
        console.log(`calling ${this.filterText} ${this.isCompleted}`)
        this.taskService.fetchTask(this.filterText, this.isCompleted)
            .subscribe((data) => {
                this.tasks = data.map(item => item);
            })
    }

    public clear() {
        this.filterText = ''
        this.updateTasks()
    }


    public completeTask(task: Task) {
        task.completed = !task.completed
        this.taskService.updateTask(task)
            .subscribe(response => {
                this.updateTasks()
            })
    }

    public markTaskAsUnsaved(task: Task) {
        task.hasUpdated = true
    }

    public updateSpecificTask(task: Task, message: string) {
        task.message = message
        this.taskService.updateTask(task)
            .subscribe(response => {
                this.updateTasks()
            })
    }

    public removeSpecificTask(task: Task) {
        console.log(`removeSpecificTask`, task)
        this.taskService.removeTask(task)
            .subscribe(response => {
                this.updateTasks()
            })
    }

    public createNewTask() {
        this.taskService.createTask()
            .subscribe(response => {
                this.updateTasks()
            })
    }

    public updateFilter(value: string) {
        if (value == '')
            this.isCompleted = null
        else if (value == 'true')
            this.isCompleted = true
        else if (value == 'false')
            this.isCompleted = false

        this.updateTasks()
    }

    public onKeydownHandler(event: any, task: Task, message: string): void {
        if (event.key === "Enter") {
            this.updateSpecificTask(task, message)
        } else {
            this.markTaskAsUnsaved(task)
        }
    }
}

<div class="body">
    <div>
        <input type="radio" (change)="updateFilter('')" id="All" value="" checked name="isCompleted">
        <label for="All">All</label>
        <input type="radio" (change)="updateFilter('true')" id="Completed" value="true" name="isCompleted">
        <label>Completed</label>
        <input type="radio" (change)="updateFilter('false')" id="Uncompleted" value="false" name="isCompleted">
        <label>Uncompleted</label>
    </div>
    <img alt="Vue logo" src="./assets/todo.png" class="logo">
    <div>
        <input size="50" [(ngModel)]="filterText"
               (ngModelChange)="updateTasks()"
               [ngClass]="{'css-input': true}"
               placeholder="Enter your search criteria">
        <div>
            <button [ngClass]="{ 'coolButton': true }" (click)="updateTasks()">SEARCH</button>
            <button [ngClass]="{ 'coolButton': true }" (click)="clear()">CLEAR</button>
        </div>
    </div>
    <br/>
    <br/>
    <br/>

    <ul *ngFor="let task of tasks" [id]="task.id">
        <input #id
               [ngClass]="{
               'completed':task.completed ? 'completed': '',
               'changed':task.hasUpdated ? 'changed': '',
               'css-input': true
               }"
               value="{{task.message}}"
               (keydown)="onKeydownHandler($event,task,id.value)"
        />
        <div>
            <button [ngClass]="{ 'coolButton': true }" (click)="completeTask(task)">check</button>
            <button [ngClass]="{ 'coolButton': true }" (click)="removeSpecificTask(task)">remove</button>
            <button [ngClass]="{ 'coolButton': true }" (click)="updateSpecificTask(task, id.value)">update</button>

        </div>
    </ul>

    <div >
            <button [ngClass]="{ 'coolButton': true ,'coolButton-green': true }" (click)="createNewTask()">Add</button>
    </div>


</div>
